### ISSUE TITLE
チャットグループのメンバー編集

### ISSUE THREAD

**Issue by Teeeeeth** [mayuki/ChatworkExtension#9]
自分の環境ですと、チャットグループのメンバー編集(追加)する際、
メンバーリストに何も表示されなくなれ、編集(追加)が行なえません。

**Comment by mayuki** [comment]
本日配信した 0.37564.21 にて修正されていますのでご確認くださいませ。

**Comment by Teeeeeth** [comment]
ありがとうございます！
